version: '3'

services:
  livraria_database:
    image: postgres
    restart: always
    expose:
      - 5432
    env_file:
      - livraria_database.env

  livraria_app:
    image: henriquefuchs/online-bookstore-rest-api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - livraria_database
    env_file:
      - livraria_app.env
