CREATE TABLE AUTORES
(
  ID              BIGINT AUTO_INCREMENT,
  NOME            VARCHAR(255) NOT NULL,
  EMAIL           VARCHAR(255) NOT NULL,
  DATA_NASCIMENTO DATE         NOT NULL,
  MINI_CURRICULO  VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE LIVROS
(
  ID              BIGINT AUTO_INCREMENT,
  TITULO          VARCHAR(255) NOT NULL,
  DATA_LANCAMENTO DATE         NOT NULL,
  NUMERO_PAGINAS  INT          NOT NULL,
  AUTOR           BIGINT       NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (AUTOR) REFERENCES AUTORES (ID)
);